### ISSUE TITLE
Log not working

### ISSUE THREAD

**Issue by wiljums** [darkrain-nl/home-assistant-addon-s0pcm-reader#18]
Error: Ophalen van het logboek van de add-on is mislukt: No systemd-journal-gatewayd Unix socket available

(addon version 0.8.5 using HA Supervisor)

**Comment by darkrain-nl** [comment]
Hi wiljums,

Is this with the new version released today?

It does work for me, so we again need to figure out what the difference is with your environment...

**Comment by darkrain-nl** [comment]
This leads me to believe it is not an addon specific issue... https://www.reddit.com/r/homeassistant/comments/1ci66p1/failed_to_get_addon_logs_no/

**Comment by darkrain-nl** [comment]
btw there is also the s0pcm-reader.log file with the log in /share/s0pcm, does that still contain the log?

**Comment by wiljums** [comment]
> btw there is also the s0pcm-reader.log file with the log in /share/s0pcm, does that still contain the log?

Yes, log is there.

**Comment by darkrain-nl** [comment]
Good to know, then there is at least a way to see the log :-)

Not sure what I can to do fix this though... Need to look into it and see if there is maybe a bug report in Home Assistant itself...

**Comment by darkrain-nl** [comment]
Hi @wiljums please have a look at https://github.com/home-assistant/supervisor/issues/5056#issuecomment-2095634535 There were some changes in the Supervisor packages that are causing this.

As it is not something I can fix I close this issue now.
