### ISSUE TITLE
Error on starting

### ISSUE THREAD

**Issue by wiljums** [darkrain-nl/home-assistant-addon-s0pcm-reader#4]
I get this error when starting the plugin, any idea how to fix?

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
/package/admin/s6-overlay-3.1.1.0/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/config.sh: Permission denied
cont-init: info: /etc/cont-init.d/config.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by darkrain-nl** [comment]
Hi wiljums,

The error is about line 14 in config.sh on that line a folder is created in the following location on Home Assistance OS:
``` /share ``` 

The error tells us it has no permission to do so.

**Comment by wiljums** [comment]
What should I do to fix this? I am running Home Assistant Supervisor in Docker on RPI4

**Comment by darkrain-nl** [comment]
If you run Supervisor this add-on will not work, it is an Add-on which needs to be loaded in Home Assistant OS...

**Comment by darkrain-nl** [comment]
Hmm let's try to get it to work, cause I would say it can work ;-)

Please check if the folder /share exists.

I have not tested this on Supervisor, so we may need to do some experimenting....

**Comment by wiljums** [comment]
Within the folder .../config/ which I can edit with the File editor (add-on)?

**Comment by darkrain-nl** [comment]
No I would say on the same level as the /config folder..

**Comment by wiljums** [comment]
share folder exists, is empty

**Comment by darkrain-nl** [comment]
OK then the easiest next step is to manually run the follow command:
``` mkdir /share/s0pcm ```

To see if it is possible to create the folder manually, if not the permissions need to be fixed.
If it can create the folder, please check if it will start now, there might be different errors, cause the script will create files inside the folder as well...

**Comment by wiljums** [comment]
I created the folder, but using Samba add-on (I actually dont know how to find te folder using putty/ssh)

**Comment by darkrain-nl** [comment]
That is fine, what does it tell you know?

**Comment by wiljums** [comment]
Still the same:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
/package/admin/s6-overlay-3.1.1.0/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/config.sh: Permission denied
cont-init: info: /etc/cont-init.d/config.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by darkrain-nl** [comment]
Hmm looks like I have to setup a test environment so I can actually test it and see what is wrong...

I can do that, but it will take a while (need to work as well ;-) )

**Comment by wiljums** [comment]
appreciate your help

**Comment by darkrain-nl** [comment]
Btw are those logs from the Log tab of the add-on? If not I would like to see those as well, but please put the log level on Debug first..

**Comment by wiljums** [comment]
These are from the log of the add-on with debug on

**Comment by darkrain-nl** [comment]
Thanks for confirming, I shall setup a system with HA Supervisor now and see if I can get it to work...
As said this can take a day or two to complete, just wanting to set expectations right.

**Comment by darkrain-nl** [comment]
The good news is I can now replicate the issue, now starting to figure out why this happens with this add-on and not with others...

**Comment by darkrain-nl** [comment]
It might have been fixed with v0.3.9, can you please test it?

**Comment by wiljums** [comment]
looks like its working!

**Comment by darkrain-nl** [comment]
That is good news, it was a change in the used S6-Overlay, updated from v2 to v3 which caused this issue.

So I'll close this tissue now.

Thanks for reporting this!
