### ISSUE TITLE
measurement.yaml not created

### ISSUE THREAD

**Issue by wiljums** [darkrain-nl/home-assistant-addon-s0pcm-reader#7]
I added this addon to a second HA instance, but the measurement.yaml file is not created. could that be because nothing is measured yet? The s0pcm reader hasn't received any pulses yet since installation of the addon.

**Comment by darkrain-nl** [comment]
Yes that makes sense, let's see what it does after some data is measured..

**Comment by wiljums** [comment]
this morning the file was created.

**Comment by darkrain-nl** [comment]
Thanks for the feedback :-)
