### ISSUE TITLE
S0PCM Reader fails with message: ERROR: MQTT failed to connect to broker 'Connection Refused: unacceptable protocol version.', retrying.

### ISSUE THREAD

**Issue by RSHKwee** [darkrain-nl/home-assistant-addon-s0pcm-reader#8]
Since 11 februari 2023 the s0pcm-reader fails to work.
I have performed a restart of HA and this is the logging:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-02-15 11:28:35,142 ERROR: MQTT failed to connect to broker 'Connection Refused: unacceptable protocol version.', retrying.
2023-02-15 11:29:34,267 ERROR: MQTT failed to connect to broker 'Connection Refused: unacceptable protocol version.', retrying.
2023-02-15 11:32:54,783 ERROR: MQTT failed to connect to broker 'Connection Refused: unacceptable protocol version.', retrying.
2023-02-15 12:16:19,643 ERROR: MQTT failed to connect to broker 'Connection Refused: unacceptable protocol version.', retrying.

How can I solve this?
I have performed a Rollback to the state of 10 feb 2023.
This is the logging I get:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/config.sh
cont-init: info: /etc/cont-init.d/config.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

And it works now....

With kind regards,

René Kwee

**Comment by darkrain-nl** [comment]
Hi René,

Thanks for raising this, let me ask a few questions (it still works for me so we need to find what causes this)...

What version of the Mosquito broker Add-on you use? (should be 6.1.3)
Also what version of Home Assistant? (my working version is 2023.2.4)
Last but not least the version of the S0PCM Reader Add-on should be 0.3.13

Please check those first, if they are all the same we need to dive deeper...

Thanks, kind regards,
Jan

**Comment by RSHKwee** [comment]
Hi Jan,

It works with (rollbacked version):
- Mosquito broker version 6.1.3
- S0PCM Reader add-on 0.3.13
- Home Assistant 2023.1.7
- Home Assistant OS 9.4

I am now performing an upgrade to:
- Home Assistant 2023.2.4
- Home Assistant OS 9.5

And it seems to work now.

**Comment by RSHKwee** [comment]
Thanks, seems like upgrading Home Assistant and Home Assistant OS did it.

**Comment by darkrain-nl** [comment]
Thanks René!
