### ISSUE TITLE
can not install s0pcm reader anymore

### ISSUE THREAD

**Issue by Digirikkie** [darkrain-nl/home-assistant-addon-s0pcm-reader#9]
A message appears during install proces: 

The command '/bin/ash -o pipefail -c pip install --no-cache-dir -r /usr/src/requirements.txt && chmod a+x /usr/src/run.sh' returned a non-zero code: 1

My versions for required packages are

Paho-mqtt  1.6.1
Pyserial  3.5
Pyyaml  6.0.1

Is this a know bug? Before the odroid update i was able to install it. Now after upgrade, remove add-on not possible to install it.

Thx

Rik

**Comment by darkrain-nl** [comment]
Thanks for reporting, I will check this soon.

I'll report back in a short while.

**Comment by darkrain-nl** [comment]
Short update, I can reproduce the error, let's see if I can find a fix for it...

**Comment by darkrain-nl** [comment]
I just released version 0.6.0 which contains the fix for this issue.

**Comment by Digirikkie** [comment]
HelloThanks for the quick fixRikVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: darkrain-nl ***@***.***> Datum: 23/07/2023  08:58  (GMT+01:00) Aan: darkrain-nl/home-assistant-addon-s0pcm-reader ***@***.***> Cc: Digirikkie ***@***.***>, Author ***@***.***> Onderwerp: Re: [darkrain-nl/home-assistant-addon-s0pcm-reader] can not install s0pcm reader anymore (Issue #9) 
I just released version 0.6.0 which contains the fix for this issue.
